CREATE TABLE IF NOT EXISTS "outgoing_media_files" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token" varchar(128) UNIQUE NOT NULL,
  "outgoing_message_id" bigint REFERENCES "outgoing_messages" ("id") ON DELETE CASCADE,
  "content_type" varchar(100) NOT NULL,
  "data" bytea NOT NULL,
  "expires_at" timestamp NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT TIMEZONE('America/Lima', NOW())
);

CREATE INDEX IF NOT EXISTS "idx_outgoing_media_files_token"
  ON "outgoing_media_files" ("token");

CREATE INDEX IF NOT EXISTS "idx_outgoing_media_files_expires_at"
  ON "outgoing_media_files" ("expires_at");
