CREATE TABLE "usuarios" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "whatsapp_jid" varchar(50) UNIQUE NOT NULL,
  "numero_whatsapp" varchar(20) UNIQUE NOT NULL,
  "creado_en" timestamp,
  "actualizado_en" timestamp
);

CREATE TABLE "incoming_messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "provider_message_id" varchar(255) UNIQUE NOT NULL,
  "usuario_id" bigint,
  "webhook_payload" jsonb NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "locked_at" timestamp,
  "error_detail" text,
  "retry_count" int NOT NULL DEFAULT 0,
  "conflict_count" int NOT NULL DEFAULT 0,
  "transient_error_count" int NOT NULL DEFAULT 0,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "conversation_state" (
  "usuario_id" bigint PRIMARY KEY NOT NULL,
  "mode" varchar(30) NOT NULL DEFAULT 'active_chat',
  "awaiting_field_code" varchar(50),
  "awaiting_question_code" varchar(10),
  "last_provider_message_id" varchar(255),
  "last_turn_at" timestamp,
  "last_form_prompt_at" timestamp,
  "turns_since_last_prompt" int NOT NULL DEFAULT 0,
  "closure_score" int,
  "reply_resolved_something" boolean NOT NULL DEFAULT false,
  "profile_completion_pct" int NOT NULL DEFAULT 0,
  "usability_completion_pct" int NOT NULL DEFAULT 0,
  "last_openai_response_id" varchar(255),
  "version" int NOT NULL DEFAULT 1,
  "onboarding_status" varchar(20) NOT NULL DEFAULT 'not_started',
  "onboarding_step" varchar(50),
  "onboarding_last_invited_at" timestamp,
  "onboarding_next_eligible_at" timestamp,
  "onboarding_skip_count" int NOT NULL DEFAULT 0,
  "onboarding_updated_at" timestamp,
  "meaningful_interactions_count" int NOT NULL DEFAULT 0,
  "updated_at" timestamp
);

CREATE TABLE "profile_extractions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" bigint NOT NULL,
  "field_code" varchar(50) NOT NULL,
  "raw_value" text NOT NULL,
  "normalized_value" varchar(500),
  "confidence" decimal(4,2) NOT NULL,
  "evidence_text" text NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'tentative',
  "resolved_entity_type" varchar(30),
  "resolved_entity_code" varchar(60),
  "resolution_strategy" varchar(20),
  "semantic_cache_hit" boolean NOT NULL DEFAULT false,
  "extracted_at" timestamp
);

CREATE TABLE "extraction_jobs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" bigint NOT NULL,
  "raw_text" text NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "retry_count" int NOT NULL DEFAULT 0,
  "locked_at" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "outgoing_messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idempotency_key" varchar(255) UNIQUE NOT NULL,
  "usuario_id" bigint NOT NULL,
  "phone" varchar(20) NOT NULL,
  "content_type" varchar(20) NOT NULL,
  "content" text NOT NULL,
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "attempt_count" int NOT NULL DEFAULT 0,
  "locked_at" timestamp,
  "sent_at" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp,
  "payload_json" jsonb,
  "scheduled_at" timestamp,
  "last_attempt_at" timestamp,
  "error_detail" text,
  "provider_response" jsonb,
  "provider_delivery_id" varchar(255)
);

CREATE TABLE "memoria_chat" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" bigint UNIQUE NOT NULL,
  "resumen" text,
  "temas_clave" text,
  "ultima_recomendacion" text,
  "modo_respuesta_preferido" varchar(20),
  "ultima_interaccion" timestamp,
  "actualizado_en" timestamp,
  "historial_mensajes" jsonb
);

CREATE TABLE "mae_departamento" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_departamento" char(2) UNIQUE NOT NULL,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "mae_provincia" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_provincia" char(4) UNIQUE NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "departamento_id" bigint NOT NULL,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "mae_distrito" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ubigeo" char(6) UNIQUE NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "provincia_id" bigint NOT NULL,
  "poblacion" int,
  "superficie" decimal(12,2),
  "latitud" decimal(10,6),
  "longitud" decimal(10,6),
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "mae_enfermedad_cie10" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_cie10" varchar(10) UNIQUE NOT NULL,
  "nombre" varchar(255) NOT NULL,
  "categoria" varchar(100),
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "mae_grupo_nutricional" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(50) UNIQUE NOT NULL,
  "nombre" varchar(150) UNIQUE NOT NULL,
  "descripcion" text,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "mae_patron_alimentario" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(50) UNIQUE NOT NULL,
  "nombre" varchar(150) UNIQUE NOT NULL,
  "descripcion" text,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "mae_dieta_terapeutica" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(50) UNIQUE NOT NULL,
  "nombre" varchar(150) UNIQUE NOT NULL,
  "categoria" varchar(100),
  "descripcion" text,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "mae_textura_dieta" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(50) UNIQUE NOT NULL,
  "nombre" varchar(150) UNIQUE NOT NULL,
  "descripcion" text,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "mae_restriccion_alimentaria" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(50) UNIQUE NOT NULL,
  "nombre" varchar(150) UNIQUE NOT NULL,
  "tipo" varchar(50) NOT NULL,
  "descripcion" text,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "mae_objetivo_nutricional" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(50) UNIQUE NOT NULL,
  "nombre" varchar(150) UNIQUE NOT NULL,
  "descripcion" text,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "rel_enfermedad_grupo_nutricional" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "enfermedad_id" bigint NOT NULL,
  "grupo_nutricional_id" bigint NOT NULL,
  "tipo_relacion" varchar(30) NOT NULL,
  "observacion" text,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "rel_grupo_nutricional_dieta" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grupo_nutricional_id" bigint NOT NULL,
  "dieta_terapeutica_id" bigint NOT NULL,
  "prioridad" int NOT NULL DEFAULT 1,
  "tipo_relacion" varchar(30) NOT NULL,
  "observacion" text,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "rel_grupo_nutricional_restriccion" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grupo_nutricional_id" bigint NOT NULL,
  "restriccion_id" bigint NOT NULL,
  "prioridad" int NOT NULL DEFAULT 1,
  "obligatoria" boolean NOT NULL DEFAULT false,
  "observacion" text,
  "activo" boolean NOT NULL DEFAULT true
);

CREATE TABLE "perfil_nutricional" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" bigint UNIQUE NOT NULL,
  "edad_reportada" int,
  "fecha_referencia_edad" date,
  "sexo" varchar(20),
  "patron_alimentario_id" bigint,
  "objetivo_nutricional_id" bigint,
  "distrito_id" bigint,
  "fuente_ubicacion" varchar(50),
  "observacion_general" text,
  "skipped_fields" jsonb,
  "creado_en" timestamp,
  "actualizado_en" timestamp
);

CREATE TABLE "perfil_nutricional_medicion" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "perfil_nutricional_id" bigint NOT NULL,
  "tipo_medicion" varchar(30) NOT NULL,
  "valor_decimal" decimal(10,2) NOT NULL,
  "unidad" varchar(20) NOT NULL,
  "fecha_medicion" timestamp NOT NULL,
  "es_valor_actual" boolean NOT NULL DEFAULT false,
  "origen" varchar(30) NOT NULL,
  "observacion" text,
  "creado_en" timestamp
);

CREATE TABLE "perfil_nutricional_enfermedad" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "perfil_nutricional_id" bigint NOT NULL,
  "enfermedad_id" bigint NOT NULL,
  "es_principal" boolean NOT NULL DEFAULT false,
  "origen" varchar(30) NOT NULL,
  "grado_confianza" decimal(4,2),
  "validado" boolean NOT NULL DEFAULT false,
  "fecha_inicio" date,
  "fecha_fin" date,
  "vigente" boolean NOT NULL DEFAULT true,
  "observacion" text,
  "creado_en" timestamp
);

CREATE TABLE "perfil_nutricional_restriccion" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "perfil_nutricional_id" bigint NOT NULL,
  "restriccion_id" bigint NOT NULL,
  "obligatoria" boolean NOT NULL DEFAULT false,
  "severidad" varchar(30),
  "validado" boolean NOT NULL DEFAULT false,
  "origen" varchar(30) NOT NULL,
  "grado_confianza" decimal(4,2),
  "fecha_inicio" date,
  "fecha_fin" date,
  "vigente" boolean NOT NULL DEFAULT true,
  "observacion" text,
  "creado_en" timestamp
);

CREATE TABLE "orden_dietetica" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "perfil_nutricional_id" bigint NOT NULL,
  "codigo" varchar(50) UNIQUE,
  "estado" varchar(30) NOT NULL,
  "textura_dieta_id" bigint,
  "fecha_inicio" timestamp NOT NULL,
  "fecha_fin" timestamp,
  "vigente" boolean NOT NULL DEFAULT true,
  "indicada_por" varchar(100),
  "fuente_orden" varchar(30) NOT NULL,
  "observacion" text,
  "creado_en" timestamp,
  "actualizado_en" timestamp
);

CREATE TABLE "orden_dietetica_dieta" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orden_dietetica_id" bigint NOT NULL,
  "dieta_terapeutica_id" bigint NOT NULL,
  "es_principal" boolean NOT NULL DEFAULT false,
  "prioridad" int NOT NULL DEFAULT 1,
  "observacion" text,
  "activo" boolean NOT NULL DEFAULT true,
  "creado_en" timestamp
);

CREATE TABLE "orden_dietetica_restriccion" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orden_dietetica_id" bigint NOT NULL,
  "restriccion_id" bigint NOT NULL,
  "obligatoria" boolean NOT NULL DEFAULT true,
  "severidad" varchar(30),
  "observacion" text,
  "activo" boolean NOT NULL DEFAULT true,
  "creado_en" timestamp
);

CREATE TABLE "mae_alias_semantico" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "entidad_tipo" varchar(30) NOT NULL,
  "entidad_codigo" varchar(60) NOT NULL,
  "alias_texto" varchar(255) NOT NULL,
  "alias_normalizado" varchar(255) NOT NULL,
  "idioma" varchar(10) NOT NULL DEFAULT 'es',
  "es_canonico" boolean NOT NULL DEFAULT false,
  "prioridad" int NOT NULL DEFAULT 1,
  "activo" boolean NOT NULL DEFAULT true,
  "creado_en" timestamp,
  "actualizado_en" timestamp
);

CREATE TABLE "semantic_catalog" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "entidad_tipo" varchar(30) NOT NULL,
  "entidad_codigo" varchar(60) NOT NULL,
  "alias_semantico_id" bigint,
  "nombre_canonico" varchar(255) NOT NULL,
  "texto_busqueda" varchar(255) NOT NULL,
  "texto_normalizado" varchar(255) NOT NULL,
  "peso_lexico" decimal(4,2) NOT NULL DEFAULT 1,
  "peso_semantico" decimal(4,2) NOT NULL DEFAULT 1,
  "embedding" varchar,
  "embedding_model" varchar(100),
  "activo" boolean NOT NULL DEFAULT true,
  "generado_en" timestamp,
  "actualizado_en" timestamp
);

CREATE TABLE "semantic_resolution_cache" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "scope" varchar(30) NOT NULL,
  "field_code" varchar(50),
  "query_texto" text NOT NULL,
  "query_normalizada" varchar(500) NOT NULL,
  "entidad_tipo_resuelta" varchar(30),
  "entidad_codigo_resuelto" varchar(60),
  "estrategia_usada" varchar(20) NOT NULL,
  "confidence" decimal(4,2) NOT NULL,
  "compatible_con_reglas" boolean NOT NULL DEFAULT true,
  "top_candidates_json" jsonb,
  "hit_count" int NOT NULL DEFAULT 0,
  "expires_at" timestamp,
  "creado_en" timestamp,
  "actualizado_en" timestamp
);

CREATE TABLE "semantic_match_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" bigint,
  "incoming_message_id" bigint,
  "scope" varchar(30) NOT NULL,
  "field_code" varchar(50),
  "query_texto" text NOT NULL,
  "query_normalizada" varchar(500) NOT NULL,
  "estrategia_usada" varchar(20) NOT NULL,
  "exact_match" boolean NOT NULL DEFAULT false,
  "trigram_score" decimal(5,4),
  "vector_score" decimal(5,4),
  "confidence_final" decimal(4,2),
  "entidad_tipo_resuelta" varchar(30),
  "entidad_codigo_resuelto" varchar(60),
  "escalado_a_ia" boolean NOT NULL DEFAULT false,
  "decidido_por_regla" boolean NOT NULL DEFAULT false,
  "latency_ms" int,
  "error_detail" text,
  "creado_en" timestamp
);

CREATE TABLE "semantic_review_queue" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" bigint,
  "incoming_message_id" bigint,
  "scope" varchar(30) NOT NULL,
  "field_code" varchar(50),
  "query_texto" text NOT NULL,
  "query_normalizada" varchar(500) NOT NULL,
  "top_candidates_json" jsonb,
  "razon" varchar(50) NOT NULL,
  "estado" varchar(20) NOT NULL,
  "resolucion_manual_tipo" varchar(30),
  "resolucion_manual_codigo" varchar(60),
  "observacion" text,
  "creado_en" timestamp,
  "resuelto_en" timestamp
);

CREATE TABLE "embedding_jobs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "source_table" varchar(50) NOT NULL,
  "source_id" bigint NOT NULL,
  "texto_fuente" text NOT NULL,
  "modelo" varchar(100) NOT NULL,
  "estado" varchar(20) NOT NULL,
  "retry_count" int NOT NULL DEFAULT 0,
  "error_detail" text,
  "creado_en" timestamp,
  "actualizado_en" timestamp,
  "procesado_en" timestamp
);

CREATE TABLE "formularios" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(100) NOT NULL,
  "nombre" varchar(200) NOT NULL,
  "version" int NOT NULL,
  "activo" boolean NOT NULL DEFAULT true,
  "fecha_inicio" timestamp,
  "fecha_cierre" timestamp,
  "creado_en" timestamp
);

CREATE TABLE "formulario_en_progreso" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "formulario_id" bigint NOT NULL,
  "usuario_id" bigint UNIQUE NOT NULL,
  "estado_actual" varchar(50) NOT NULL,
  "respuestas_parciales" jsonb,
  "uso_audio" boolean NOT NULL DEFAULT false,
  "uso_imagen" boolean NOT NULL DEFAULT false,
  "iniciado_en" timestamp,
  "actualizado_en" timestamp,
  "completado_en" timestamp,
  "audio_test_requested" boolean NOT NULL DEFAULT false,
  "audio_test_completed" boolean NOT NULL DEFAULT false,
  "audio_test_declined" boolean NOT NULL DEFAULT false,
  "image_test_requested" boolean NOT NULL DEFAULT false,
  "image_test_completed" boolean NOT NULL DEFAULT false,
  "image_test_declined" boolean NOT NULL DEFAULT false
);

CREATE TABLE "respuestas_formulario" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "formulario_id" bigint NOT NULL,
  "usuario_id" bigint NOT NULL,
  "correo" varchar(255) NOT NULL,
  "telefono" varchar(30),
  "edad" int,
  "asegurado_essalud" varchar(20),
  "comentario" text,
  "autorizo_uso_investigacion" boolean,
  "puntaje_nps" int,
  "creado_en" timestamp,
  "audio_evaluado" boolean NOT NULL DEFAULT false,
  "audio_no_aplica" boolean NOT NULL DEFAULT false,
  "imagen_evaluada" boolean NOT NULL DEFAULT false,
  "imagen_no_aplica" boolean NOT NULL DEFAULT false,
  "correo_proporcionado" boolean NOT NULL DEFAULT false
);

CREATE TABLE "evaluacion_usabilidad" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "respuesta_formulario_id" bigint UNIQUE NOT NULL,
  "p1_personalidad_realista_atractiva" int,
  "p2_explico_proposito_alcance" int,
  "p3_facil_navegar" int,
  "p4_me_entendio_bien" int,
  "p5_respuestas_utiles_apropiadas_informativas" int,
  "p6_manejo_errores_equivocaciones" int,
  "p7_muy_facil_de_usar" int,
  "p8_audio_claridad" int,
  "p9_reconocio_contexto_imagen" int,
  "p10_se_enfoco_en_nutricion" int,
  "creado_en" timestamp
);

CREATE TABLE "documentos_rag" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "tipo_fuente" varchar(30),
  "archivo_url" text,
  "descripcion" text,
  "estado" varchar(20),
  "creado_en" timestamp,
  "actualizado_en" timestamp
);

CREATE TABLE "fragmentos_rag" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "documento_id" bigint NOT NULL,
  "pagina" int,
  "numero_fragmento" int NOT NULL,
  "contenido" text NOT NULL,
  "metadata" jsonb,
  "embedding" varchar,
  "creado_en" timestamp
);

CREATE TABLE "campanias" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar(255) NOT NULL,
  "descripcion" text,
  "tipo" varchar(30),
  "fecha_inicio" timestamp,
  "fecha_fin" timestamp,
  "distrito_id" bigint,
  "lugar" varchar(255),
  "creado_en" timestamp
);

CREATE UNIQUE INDEX ON "mae_provincia" ("departamento_id", "nombre");

CREATE UNIQUE INDEX ON "mae_distrito" ("provincia_id", "nombre");

CREATE UNIQUE INDEX ON "rel_enfermedad_grupo_nutricional" ("enfermedad_id", "grupo_nutricional_id");

CREATE UNIQUE INDEX ON "rel_grupo_nutricional_dieta" ("grupo_nutricional_id", "dieta_terapeutica_id");

CREATE UNIQUE INDEX ON "rel_grupo_nutricional_restriccion" ("grupo_nutricional_id", "restriccion_id");

CREATE UNIQUE INDEX ON "perfil_nutricional_enfermedad" ("perfil_nutricional_id", "enfermedad_id");

CREATE UNIQUE INDEX ON "perfil_nutricional_restriccion" ("perfil_nutricional_id", "restriccion_id");

CREATE UNIQUE INDEX ON "orden_dietetica_dieta" ("orden_dietetica_id", "dieta_terapeutica_id");

CREATE UNIQUE INDEX ON "orden_dietetica_restriccion" ("orden_dietetica_id", "restriccion_id");

CREATE UNIQUE INDEX ON "mae_alias_semantico" ("entidad_tipo", "entidad_codigo", "alias_normalizado");

CREATE INDEX ON "mae_alias_semantico" ("entidad_tipo", "alias_normalizado");

CREATE UNIQUE INDEX ON "semantic_catalog" ("entidad_tipo", "entidad_codigo", "texto_normalizado");

CREATE INDEX ON "semantic_catalog" ("entidad_tipo", "texto_normalizado");

CREATE UNIQUE INDEX ON "semantic_resolution_cache" ("scope", "field_code", "query_normalizada");

CREATE UNIQUE INDEX ON "embedding_jobs" ("source_table", "source_id", "modelo");

CREATE UNIQUE INDEX ON "formularios" ("codigo", "version");

CREATE UNIQUE INDEX ON "respuestas_formulario" ("formulario_id", "usuario_id");

CREATE UNIQUE INDEX ON "fragmentos_rag" ("documento_id", "numero_fragmento");

COMMENT ON TABLE "usuarios" IS 'TABLA: usuarios

QUÉ ES:
Tabla maestra central de identidad del usuario dentro del sistema.

PARA QUÉ SIRVE:
- Unificar perfil nutricional, conversación, memoria y colas.
- Evitar duplicar usuarios por cada mensaje recibido.
- Tener un ancla estable para toda la operación.

QUÉ DEBE IR AQUÍ:
- Solo identidad técnica y mínima del usuario.
- No debe guardar enfermedades, dietas, alergias ni historial conversacional detallado.

QUÉ NO DEBE IR AQUÍ:
- Datos nutricionales
- Resúmenes clínicos
- Estado de conversación
- Mensajes o documentos
';

COMMENT ON COLUMN "usuarios"."id" IS 'Clave primaria interna del usuario. Todas las tablas de perfil, conversación y colas se anclan a este ID.';

COMMENT ON COLUMN "usuarios"."whatsapp_jid" IS 'Identificador completo del usuario en WhatsApp. Ejemplo: 51999999999@s.whatsapp.net. Sirve para integrar con el proveedor de mensajería.';

COMMENT ON COLUMN "usuarios"."numero_whatsapp" IS 'Número telefónico limpio del usuario, normalmente sin espacios ni símbolos. Sirve para búsquedas y para el envío de mensajes.';

COMMENT ON COLUMN "usuarios"."creado_en" IS 'Fecha en la que el usuario fue creado por primera vez en el sistema.';

COMMENT ON COLUMN "usuarios"."actualizado_en" IS 'Última vez que se actualizó algún dato de esta fila del usuario.';

COMMENT ON TABLE "incoming_messages" IS 'TABLA: incoming_messages

QUÉ ES:
Inbox operacional de mensajes entrantes.

PARA QUÉ SIRVE:
- Recibir mensajes del proveedor de mensajería.
- Evitar procesamiento duplicado.
- Permitir reintentos y trazabilidad.
- Separar recepción del procesamiento.

QUÉ DEBE IR AQUÍ:
- El mensaje recibido como evento técnico.
- El payload bruto del webhook.
- Estado de procesamiento.

QUÉ NO DEBE IR AQUÍ:
- Respuestas del bot
- Resumen conversacional
- Datos clínicos ya estructurados
';

COMMENT ON COLUMN "incoming_messages"."id" IS 'Clave primaria interna del mensaje recibido.';

COMMENT ON COLUMN "incoming_messages"."provider_message_id" IS 'ID único del mensaje entregado por el proveedor de WhatsApp o el gateway. Se usa para deduplicación e idempotencia.';

COMMENT ON COLUMN "incoming_messages"."usuario_id" IS 'Usuario asociado al mensaje si ya pudo resolverse. Puede venir nulo en etapas muy tempranas si aún no se identificó al usuario.';

COMMENT ON COLUMN "incoming_messages"."webhook_payload" IS 'Payload bruto completo del webhook recibido. Debe guardarse tal cual para auditoría, reprocesamiento o depuración.';

COMMENT ON COLUMN "incoming_messages"."status" IS 'Estado operativo del procesamiento del mensaje: pending, processing, done, failed.';

COMMENT ON COLUMN "incoming_messages"."locked_at" IS 'Momento en el que un worker tomó este mensaje para procesarlo. Sirve para control de concurrencia y reintentos.';

COMMENT ON COLUMN "incoming_messages"."error_detail" IS 'Último error registrado al procesar el mensaje. Solo debe usarse para diagnóstico técnico.';

COMMENT ON COLUMN "incoming_messages"."retry_count" IS 'Número de reintentos ejecutados sobre este mensaje.';

COMMENT ON COLUMN "incoming_messages"."conflict_count" IS 'Número de conflictos de concurrencia detectados al procesar el mensaje.';

COMMENT ON COLUMN "incoming_messages"."transient_error_count" IS 'Número de errores temporales o recuperables, por ejemplo fallos de red o tiempo de espera.';

COMMENT ON COLUMN "incoming_messages"."created_at" IS 'Momento en que el mensaje entró al inbox del sistema.';

COMMENT ON COLUMN "incoming_messages"."updated_at" IS 'Última actualización técnica de esta fila.';

COMMENT ON TABLE "conversation_state" IS 'TABLA: conversation_state

QUÉ ES:
Estado conversacional actual del usuario.

PARA QUÉ SIRVE:
- Saber qué está esperando el bot.
- Controlar onboarding y encuestas.
- Mantener continuidad entre mensajes.
- Evitar que el sistema pregunte cosas fuera de contexto.

QUÉ DEBE IR AQUÍ:
- Estado actual y operativo.
- No historial completo.
- No contenido clínico definitivo.

QUÉ NO DEBE IR AQUÍ:
- Mensajes completos
- Enfermedades confirmadas
- Dietas registradas como dato final
';

COMMENT ON COLUMN "conversation_state"."usuario_id" IS 'Clave primaria y foránea al usuario. Hay una sola fila vigente por usuario para representar su estado actual de conversación.';

COMMENT ON COLUMN "conversation_state"."mode" IS 'Modo operativo actual del diálogo. Ejemplo: active_chat o collecting_usability.';

COMMENT ON COLUMN "conversation_state"."awaiting_field_code" IS 'Código del campo de perfil o formulario que el bot está esperando actualmente. Ejemplo: edad, objetivo, distrito.';

COMMENT ON COLUMN "conversation_state"."awaiting_question_code" IS 'Código corto de la pregunta puntual que se espera en el flujo de usabilidad.';

COMMENT ON COLUMN "conversation_state"."last_provider_message_id" IS 'ID del último mensaje entrante relevante para este estado conversacional.';

COMMENT ON COLUMN "conversation_state"."last_turn_at" IS 'Fecha y hora del último turno efectivo del usuario o del sistema.';

COMMENT ON COLUMN "conversation_state"."last_form_prompt_at" IS 'Última vez que se pidió explícitamente una respuesta de formulario o encuesta.';

COMMENT ON COLUMN "conversation_state"."turns_since_last_prompt" IS 'Cantidad de turnos transcurridos desde la última pregunta de formulario. Sirve para no insistir demasiado.';

COMMENT ON COLUMN "conversation_state"."closure_score" IS 'Puntaje interno que estima intención de cierre o despedida. Puede servir para decidir si pedir datos o no.';

COMMENT ON COLUMN "conversation_state"."reply_resolved_something" IS 'Indica si la última respuesta del bot resolvió algo útil antes de intentar capturar más datos.';

COMMENT ON COLUMN "conversation_state"."profile_completion_pct" IS 'Porcentaje de avance estimado del perfil nutricional del usuario.';

COMMENT ON COLUMN "conversation_state"."usability_completion_pct" IS 'Porcentaje de avance estimado de la evaluación de usabilidad.';

COMMENT ON COLUMN "conversation_state"."last_openai_response_id" IS 'ID del último response o cadena conversacional usada con el proveedor de IA, si aplica.';

COMMENT ON COLUMN "conversation_state"."version" IS 'Versión interna para control de concurrencia optimista.';

COMMENT ON COLUMN "conversation_state"."onboarding_status" IS 'Estado general del onboarding: not_started, invited, in_progress, completed, skipped, paused.';

COMMENT ON COLUMN "conversation_state"."onboarding_step" IS 'Paso concreto del onboarding en el que está el usuario.';

COMMENT ON COLUMN "conversation_state"."onboarding_last_invited_at" IS 'Última vez que el sistema invitó al usuario a completar onboarding.';

COMMENT ON COLUMN "conversation_state"."onboarding_next_eligible_at" IS 'Próximo momento permitido para volver a invitar al usuario.';

COMMENT ON COLUMN "conversation_state"."onboarding_skip_count" IS 'Número de veces que el usuario ha omitido o rechazado el onboarding.';

COMMENT ON COLUMN "conversation_state"."onboarding_updated_at" IS 'Última vez que cambió algo relacionado al onboarding.';

COMMENT ON COLUMN "conversation_state"."meaningful_interactions_count" IS 'Contador de interacciones útiles para disparar encuestas, seguimiento o milestones.';

COMMENT ON COLUMN "conversation_state"."updated_at" IS 'Última actualización global de este estado conversacional.';

COMMENT ON TABLE "profile_extractions" IS 'TABLA: profile_extractions

QUÉ ES:
Registro de inferencias tentativas extraídas desde el chat.

PARA QUÉ SIRVE:
- No contaminar el perfil final con datos dudosos.
- Permitir validación posterior.
- Trazar de dónde salió cada inferencia.

QUÉ DEBE IR AQUÍ:
- Detecciones intermedias.
- Posibles campos de perfil.
- Señales que luego podrían confirmarse.

QUÉ NO DEBE IR AQUÍ:
- El dato definitivo del perfil si ya fue confirmado.
- Prescripciones dietéticas oficiales.
';

COMMENT ON COLUMN "profile_extractions"."id" IS 'Clave primaria interna de una extracción de perfil.';

COMMENT ON COLUMN "profile_extractions"."usuario_id" IS 'Usuario al que pertenece esta inferencia o extracción.';

COMMENT ON COLUMN "profile_extractions"."field_code" IS 'Nombre técnico del campo detectado. Ejemplo: edad, enfermedad, restriccion, objetivo, distrito.';

COMMENT ON COLUMN "profile_extractions"."raw_value" IS 'Texto exacto detectado en la conversación antes de normalizarlo.';

COMMENT ON COLUMN "profile_extractions"."normalized_value" IS 'Versión normalizada del raw_value, útil para matching semántico o fuzzy.';

COMMENT ON COLUMN "profile_extractions"."confidence" IS 'Nivel de confianza interno de la extracción, entre 0.00 y 1.00.';

COMMENT ON COLUMN "profile_extractions"."evidence_text" IS 'Fragmento textual o evidencia del mensaje que justifica la extracción.';

COMMENT ON COLUMN "profile_extractions"."status" IS 'Estado de la extracción: tentative, confirmed o rejected.';

COMMENT ON COLUMN "profile_extractions"."resolved_entity_type" IS 'Tipo de entidad maestra a la que se resolvió la extracción, si ya existe resolución.';

COMMENT ON COLUMN "profile_extractions"."resolved_entity_code" IS 'Código canónico de la entidad resuelta en el maestro correspondiente.';

COMMENT ON COLUMN "profile_extractions"."resolution_strategy" IS 'Estrategia usada para resolver la extracción: EXACT, TRGM, VECTOR, HYBRID, LLM.';

COMMENT ON COLUMN "profile_extractions"."semantic_cache_hit" IS 'Marca si la resolución vino desde cache semántico en lugar de recalcularse.';

COMMENT ON COLUMN "profile_extractions"."extracted_at" IS 'Momento en que esta extracción fue generada.';

COMMENT ON TABLE "extraction_jobs" IS 'TABLA: extraction_jobs

QUÉ ES:
Cola de trabajos para extracción semántica o estructurada del perfil.

PARA QUÉ SIRVE:
- Desacoplar el análisis del flujo de respuesta.
- Procesar texto fuera del camino crítico.
- Permitir reintentos y concurrencia controlada.

QUÉ DEBE IR AQUÍ:
- Trabajo pendiente de extracción.
- Texto fuente.
- Estado técnico del job.

QUÉ NO DEBE IR AQUÍ:
- Resultado final confirmado.
';

COMMENT ON COLUMN "extraction_jobs"."id" IS 'Clave primaria interna del job de extracción.';

COMMENT ON COLUMN "extraction_jobs"."usuario_id" IS 'Usuario cuyo texto será procesado por el pipeline de extracción.';

COMMENT ON COLUMN "extraction_jobs"."raw_text" IS 'Texto completo o fragmento que debe ser analizado para extraer información estructurada.';

COMMENT ON COLUMN "extraction_jobs"."status" IS 'Estado del job: pending, processing, done o failed.';

COMMENT ON COLUMN "extraction_jobs"."retry_count" IS 'Número de reintentos del job.';

COMMENT ON COLUMN "extraction_jobs"."locked_at" IS 'Momento en que un worker tomó este job para procesarlo.';

COMMENT ON COLUMN "extraction_jobs"."created_at" IS 'Fecha de creación del job.';

COMMENT ON COLUMN "extraction_jobs"."updated_at" IS 'Última actualización del job.';

COMMENT ON TABLE "outgoing_messages" IS 'TABLA: outgoing_messages

QUÉ ES:
Outbox de mensajes que el sistema debe enviar.

PARA QUÉ SIRVE:
- Controlar idempotencia.
- Permitir reintentos de salida.
- Separar generación de contenido del envío real.
- Trazar fallos y entregas.

QUÉ DEBE IR AQUÍ:
- Mensajes listos o pendientes de salida.
- Estado técnico de despacho.

QUÉ NO DEBE IR AQUÍ:
- El historial clínico del usuario.
- La lógica de nutrición como tal.
';

COMMENT ON COLUMN "outgoing_messages"."id" IS 'Clave primaria interna del mensaje saliente.';

COMMENT ON COLUMN "outgoing_messages"."idempotency_key" IS 'Clave única para evitar enviar dos veces el mismo mensaje por errores o reintentos.';

COMMENT ON COLUMN "outgoing_messages"."usuario_id" IS 'Usuario destinatario del mensaje.';

COMMENT ON COLUMN "outgoing_messages"."phone" IS 'Número final de destino usado para el envío.';

COMMENT ON COLUMN "outgoing_messages"."content_type" IS 'Tipo de contenido: text, audio, audio_tts, buttons, list.';

COMMENT ON COLUMN "outgoing_messages"."content" IS 'Contenido principal del mensaje. Puede ser texto plano o representación base del contenido.';

COMMENT ON COLUMN "outgoing_messages"."status" IS 'Estado del envío: pending, processing, sending, sent, failed.';

COMMENT ON COLUMN "outgoing_messages"."attempt_count" IS 'Cantidad de intentos de envío realizados.';

COMMENT ON COLUMN "outgoing_messages"."locked_at" IS 'Momento en que un worker tomó este registro para despacharlo.';

COMMENT ON COLUMN "outgoing_messages"."sent_at" IS 'Momento en que el sistema marcó este mensaje como enviado.';

COMMENT ON COLUMN "outgoing_messages"."created_at" IS 'Fecha de creación del mensaje saliente.';

COMMENT ON COLUMN "outgoing_messages"."updated_at" IS 'Última actualización de esta fila.';

COMMENT ON COLUMN "outgoing_messages"."payload_json" IS 'Payload estructurado para el proveedor si el contenido requiere botones, listas u otros formatos.';

COMMENT ON COLUMN "outgoing_messages"."scheduled_at" IS 'Fecha/hora programada de envío. Permite colas diferidas.';

COMMENT ON COLUMN "outgoing_messages"."last_attempt_at" IS 'Fecha del último intento de despacho.';

COMMENT ON COLUMN "outgoing_messages"."error_detail" IS 'Detalle del último error de envío.';

COMMENT ON COLUMN "outgoing_messages"."provider_response" IS 'Respuesta cruda del proveedor de mensajería.';

COMMENT ON COLUMN "outgoing_messages"."provider_delivery_id" IS 'ID de entrega devuelto por el proveedor.';

COMMENT ON TABLE "memoria_chat" IS 'TABLA: memoria_chat

QUÉ ES:
Memoria de largo plazo resumida del usuario.

PARA QUÉ SIRVE:
- Recordar contexto entre conversaciones.
- Evitar recalcular siempre lo mismo.
- Mejorar continuidad sin depender del historial crudo completo.

QUÉ DEBE IR AQUÍ:
- Resúmenes.
- Preferencias del usuario.
- Temas clave persistentes.

QUÉ NO DEBE IR AQUÍ:
- Registros maestros clínicos.
- Mensajes crudos completos.
';

COMMENT ON COLUMN "memoria_chat"."id" IS 'Clave primaria interna del registro de memoria.';

COMMENT ON COLUMN "memoria_chat"."usuario_id" IS 'Usuario al que pertenece esta memoria resumida.';

COMMENT ON COLUMN "memoria_chat"."resumen" IS 'Resumen corto acumulado de lo más importante que se sabe del usuario o de la conversación.';

COMMENT ON COLUMN "memoria_chat"."temas_clave" IS 'Lista o resumen de temas importantes tratados con el usuario.';

COMMENT ON COLUMN "memoria_chat"."ultima_recomendacion" IS 'Última recomendación relevante entregada al usuario.';

COMMENT ON COLUMN "memoria_chat"."modo_respuesta_preferido" IS 'Preferencia aproximada del usuario: texto, audio o mixto.';

COMMENT ON COLUMN "memoria_chat"."ultima_interaccion" IS 'Última fecha en la que hubo interacción relevante.';

COMMENT ON COLUMN "memoria_chat"."actualizado_en" IS 'Última fecha en la que se actualizó esta memoria.';

COMMENT ON COLUMN "memoria_chat"."historial_mensajes" IS 'Historial resumido o comprimido de mensajes relevantes. No debería ser el log bruto completo.';

COMMENT ON TABLE "mae_departamento" IS 'TABLA: mae_departamento

QUÉ ES:
Maestro geográfico de departamentos o regiones.

PARA QUÉ SIRVE:
- Normalizar ubicación.
- Evitar texto libre para región/departamento.
- Soportar filtros y campañas por zona geográfica.
';

COMMENT ON COLUMN "mae_departamento"."id" IS 'Clave primaria interna del departamento o región.';

COMMENT ON COLUMN "mae_departamento"."codigo_departamento" IS 'Código oficial corto del departamento, normalmente derivado del ubigeo.';

COMMENT ON COLUMN "mae_departamento"."nombre" IS 'Nombre oficial del departamento o región.';

COMMENT ON COLUMN "mae_departamento"."activo" IS 'Permite desactivar registros sin borrarlos físicamente.';

COMMENT ON TABLE "mae_provincia" IS 'TABLA: mae_provincia

QUÉ ES:
Maestro geográfico de provincias.

PARA QUÉ SIRVE:
- Ubicación estructurada.
- Dependencia jerárquica con departamento.
- Normalización para formularios, perfil y campañas.
';

COMMENT ON COLUMN "mae_provincia"."id" IS 'Clave primaria interna de la provincia.';

COMMENT ON COLUMN "mae_provincia"."codigo_provincia" IS 'Código oficial corto de la provincia, normalmente derivado del ubigeo.';

COMMENT ON COLUMN "mae_provincia"."nombre" IS 'Nombre oficial de la provincia.';

COMMENT ON COLUMN "mae_provincia"."departamento_id" IS 'Departamento al que pertenece la provincia.';

COMMENT ON COLUMN "mae_provincia"."activo" IS 'Permite mantener histórico o desactivar sin borrar.';

COMMENT ON TABLE "mae_distrito" IS 'TABLA: mae_distrito

QUÉ ES:
Maestro geográfico de distritos.

PARA QUÉ SIRVE:
- Almacenar la ubicación normalizada del usuario.
- Permitir campañas segmentadas.
- Derivar provincia y departamento sin duplicar demasiado.

NOTA DE DISEÑO:
El sistema usa distrito_id como punto principal de ubicación;
desde ahí se puede navegar hacia provincia y departamento.
';

COMMENT ON COLUMN "mae_distrito"."id" IS 'Clave primaria interna del distrito.';

COMMENT ON COLUMN "mae_distrito"."ubigeo" IS 'Código ubigeo completo del distrito.';

COMMENT ON COLUMN "mae_distrito"."nombre" IS 'Nombre oficial del distrito.';

COMMENT ON COLUMN "mae_distrito"."provincia_id" IS 'Provincia a la que pertenece el distrito.';

COMMENT ON COLUMN "mae_distrito"."poblacion" IS 'Población estimada si se desea usar contexto geográfico o analítica.';

COMMENT ON COLUMN "mae_distrito"."superficie" IS 'Superficie territorial estimada del distrito.';

COMMENT ON COLUMN "mae_distrito"."latitud" IS 'Latitud referencial del distrito.';

COMMENT ON COLUMN "mae_distrito"."longitud" IS 'Longitud referencial del distrito.';

COMMENT ON COLUMN "mae_distrito"."activo" IS 'Marca lógica de vigencia del registro.';

COMMENT ON TABLE "mae_enfermedad_cie10" IS 'TABLA: mae_enfermedad_cie10

QUÉ ES:
Maestro de enfermedades codificadas.

PARA QUÉ SIRVE:
- Representar diagnósticos o condiciones clínicas en forma estructurada.
- Relacionar enfermedades con grupos nutricionales.
- Evitar guardar enfermedades como texto libre.

QUÉ DEBE IR AQUÍ:
- Solo catálogo maestro, no el diagnóstico del usuario.
';

COMMENT ON COLUMN "mae_enfermedad_cie10"."id" IS 'Clave primaria interna del registro de enfermedad.';

COMMENT ON COLUMN "mae_enfermedad_cie10"."codigo_cie10" IS 'Código CIE10 canónico de la enfermedad.';

COMMENT ON COLUMN "mae_enfermedad_cie10"."nombre" IS 'Nombre descriptivo oficial o estandarizado de la enfermedad.';

COMMENT ON COLUMN "mae_enfermedad_cie10"."categoria" IS 'Capítulo, familia o agrupación mayor a la que pertenece la enfermedad.';

COMMENT ON COLUMN "mae_enfermedad_cie10"."activo" IS 'Permite desactivar un código sin borrarlo del sistema.';

COMMENT ON TABLE "mae_grupo_nutricional" IS 'TABLA: mae_grupo_nutricional

QUÉ ES:
Agrupador intermedio entre enfermedad y lógica nutricional.

PARA QUÉ SIRVE:
- No mapear miles de CIE10 directamente a dietas.
- Reutilizar reglas nutricionales por familia clínica.
- Simplificar mantenimiento del sistema.

EJEMPLO:
Varias enfermedades pueden pertenecer al grupo DIABETES,
y desde ese grupo derivar dietas y restricciones.
';

COMMENT ON COLUMN "mae_grupo_nutricional"."id" IS 'Clave primaria interna del grupo nutricional.';

COMMENT ON COLUMN "mae_grupo_nutricional"."codigo" IS 'Código técnico del grupo. Ejemplo: DIABETES, HIPERTENSION, RENAL.';

COMMENT ON COLUMN "mae_grupo_nutricional"."nombre" IS 'Nombre legible del grupo nutricional.';

COMMENT ON COLUMN "mae_grupo_nutricional"."descripcion" IS 'Descripción funcional del grupo y su significado clínico-nutricional.';

COMMENT ON COLUMN "mae_grupo_nutricional"."activo" IS 'Indica si el grupo sigue vigente en el modelo.';

COMMENT ON TABLE "mae_patron_alimentario" IS 'TABLA: mae_patron_alimentario

QUÉ ES:
Maestro de estilo o patrón base de alimentación del usuario.

PARA QUÉ SIRVE:
- Guardar si la persona es omnívora, vegetariana, vegana, etc.
- Separar preferencia o estilo alimentario de dietas terapéuticas.

IMPORTANTE:
Esto NO es una orden dietética clínica.
';

COMMENT ON COLUMN "mae_patron_alimentario"."id" IS 'Clave primaria interna del patrón alimentario.';

COMMENT ON COLUMN "mae_patron_alimentario"."codigo" IS 'Código técnico del patrón. Ejemplo: OMNIVORA, VEGANA.';

COMMENT ON COLUMN "mae_patron_alimentario"."nombre" IS 'Nombre legible del patrón alimentario.';

COMMENT ON COLUMN "mae_patron_alimentario"."descripcion" IS 'Descripción del patrón base de alimentación del usuario.';

COMMENT ON COLUMN "mae_patron_alimentario"."activo" IS 'Marca si el patrón está activo o disponible.';

COMMENT ON TABLE "mae_dieta_terapeutica" IS 'TABLA: mae_dieta_terapeutica

QUÉ ES:
Maestro de dietas terapéuticas o funcionales.

PARA QUÉ SIRVE:
- Representar dietas como hiposódica, renal, hipocalórica, etc.
- Ser usada por reglas y por órdenes dietéticas.

IMPORTANTE:
Esta tabla es catálogo.
No dice quién tiene esa dieta; eso lo maneja la orden dietética.
';

COMMENT ON COLUMN "mae_dieta_terapeutica"."id" IS 'Clave primaria interna de la dieta terapéutica.';

COMMENT ON COLUMN "mae_dieta_terapeutica"."codigo" IS 'Código técnico de la dieta. Ejemplo: HIPOSODICA, RENAL_GENERAL.';

COMMENT ON COLUMN "mae_dieta_terapeutica"."nombre" IS 'Nombre legible de la dieta terapéutica.';

COMMENT ON COLUMN "mae_dieta_terapeutica"."categoria" IS 'Clasificación mayor de la dieta. Ejemplo: BASE, TERAPEUTICA, PATRON_TERAPEUTICO.';

COMMENT ON COLUMN "mae_dieta_terapeutica"."descripcion" IS 'Descripción funcional de cuándo y cómo se usa esta dieta.';

COMMENT ON COLUMN "mae_dieta_terapeutica"."activo" IS 'Marca si la dieta sigue disponible en el sistema.';

COMMENT ON TABLE "mae_textura_dieta" IS 'TABLA: mae_textura_dieta

QUÉ ES:
Maestro de texturas o consistencias de alimentación.

PARA QUÉ SIRVE:
- Diferenciar una dieta por forma de presentación.
- Modelar casos como blanda, líquida, puré o disfagia.

IMPORTANTE:
La textura no reemplaza la dieta terapéutica.
Es una dimensión adicional.
';

COMMENT ON COLUMN "mae_textura_dieta"."id" IS 'Clave primaria interna de la textura o consistencia de dieta.';

COMMENT ON COLUMN "mae_textura_dieta"."codigo" IS 'Código técnico. Ejemplo: BLANDA, LIQUIDA_CLARA, TRITURADA_O_PURE.';

COMMENT ON COLUMN "mae_textura_dieta"."nombre" IS 'Nombre legible de la textura o consistencia.';

COMMENT ON COLUMN "mae_textura_dieta"."descripcion" IS 'Descripción de la consistencia y su uso clínico o funcional.';

COMMENT ON COLUMN "mae_textura_dieta"."activo" IS 'Marca si esta textura está vigente o disponible.';

COMMENT ON TABLE "mae_restriccion_alimentaria" IS 'TABLA: mae_restriccion_alimentaria

QUÉ ES:
Maestro de restricciones alimentarias.

PARA QUÉ SIRVE:
- Separar restricciones del usuario de la dieta principal.
- Reutilizar restricciones en perfil y en órdenes dietéticas.
- Representar alergias, intolerancias y restricciones clínicas.

EJEMPLOS:
- SIN_GLUTEN
- SIN_LACTOSA
- BAJA_EN_POTASIO
- HALAL
';

COMMENT ON COLUMN "mae_restriccion_alimentaria"."id" IS 'Clave primaria interna de la restricción alimentaria.';

COMMENT ON COLUMN "mae_restriccion_alimentaria"."codigo" IS 'Código técnico de la restricción. Ejemplo: SIN_GLUTEN, BAJA_EN_POTASIO.';

COMMENT ON COLUMN "mae_restriccion_alimentaria"."nombre" IS 'Nombre legible de la restricción.';

COMMENT ON COLUMN "mae_restriccion_alimentaria"."tipo" IS 'Tipo funcional de la restricción: ALERGENO, INTOLERANCIA, CLINICA, CULTURAL, PREFERENCIA.';

COMMENT ON COLUMN "mae_restriccion_alimentaria"."descripcion" IS 'Descripción de qué limita, prohíbe o controla esta restricción.';

COMMENT ON COLUMN "mae_restriccion_alimentaria"."activo" IS 'Permite desactivar la restricción sin borrarla.';

COMMENT ON TABLE "mae_objetivo_nutricional" IS 'TABLA: mae_objetivo_nutricional

QUÉ ES:
Maestro de objetivos nutricionales.

PARA QUÉ SIRVE:
- Guardar el objetivo principal del usuario.
- Orientar recomendaciones y planes.
- Separar "objetivo" de "diagnóstico" y de "dieta".

EJEMPLOS:
- pérdida de peso
- control glucosa
- mantenimiento
- recuperación nutricional
';

COMMENT ON COLUMN "mae_objetivo_nutricional"."id" IS 'Clave primaria interna del objetivo nutricional.';

COMMENT ON COLUMN "mae_objetivo_nutricional"."codigo" IS 'Código técnico del objetivo. Ejemplo: PERDIDA_PESO, CONTROL_GLUCOSA.';

COMMENT ON COLUMN "mae_objetivo_nutricional"."nombre" IS 'Nombre legible del objetivo.';

COMMENT ON COLUMN "mae_objetivo_nutricional"."descripcion" IS 'Descripción del propósito nutricional principal.';

COMMENT ON COLUMN "mae_objetivo_nutricional"."activo" IS 'Permite marcar objetivos como activos o no.';

COMMENT ON TABLE "rel_enfermedad_grupo_nutricional" IS 'TABLA: rel_enfermedad_grupo_nutricional

QUÉ ES:
Tabla puente entre enfermedad y grupo nutricional.

PARA QUÉ SIRVE:
- Traducir diagnóstico a lógica nutricional.
- Evitar mapear CIE10 directamente a dietas sin capas intermedias.
- Mantener reglas más fáciles de sostener.

EJEMPLO:
E11.9 -> grupo DIABETES
';

COMMENT ON COLUMN "rel_enfermedad_grupo_nutricional"."id" IS 'Clave primaria interna de la relación entre enfermedad y grupo nutricional.';

COMMENT ON COLUMN "rel_enfermedad_grupo_nutricional"."enfermedad_id" IS 'Enfermedad específica que pertenece o se asocia a un grupo nutricional.';

COMMENT ON COLUMN "rel_enfermedad_grupo_nutricional"."grupo_nutricional_id" IS 'Grupo nutricional al que se asocia la enfermedad.';

COMMENT ON COLUMN "rel_enfermedad_grupo_nutricional"."tipo_relacion" IS 'Nivel o fuerza de la relación: OBLIGATORIA, FRECUENTE, CONDICIONAL.';

COMMENT ON COLUMN "rel_enfermedad_grupo_nutricional"."observacion" IS 'Aclaración clínica o de negocio sobre la relación.';

COMMENT ON COLUMN "rel_enfermedad_grupo_nutricional"."activo" IS 'Permite activar o desactivar la regla sin eliminarla.';

COMMENT ON TABLE "rel_grupo_nutricional_dieta" IS 'TABLA: rel_grupo_nutricional_dieta

QUÉ ES:
Regla que conecta un grupo nutricional con una o varias dietas terapéuticas.

PARA QUÉ SIRVE:
- Generar sugerencias.
- Validar consistencia.
- Ayudar a clasificar dietas apropiadas según condición clínica.

IMPORTANTE:
Esta tabla define reglas generales, no la orden real del usuario.
';

COMMENT ON COLUMN "rel_grupo_nutricional_dieta"."id" IS 'Clave primaria interna de la relación entre grupo nutricional y dieta.';

COMMENT ON COLUMN "rel_grupo_nutricional_dieta"."grupo_nutricional_id" IS 'Grupo nutricional desde el cual parte la regla.';

COMMENT ON COLUMN "rel_grupo_nutricional_dieta"."dieta_terapeutica_id" IS 'Dieta terapéutica sugerida, obligatoria o contraindicada para el grupo.';

COMMENT ON COLUMN "rel_grupo_nutricional_dieta"."prioridad" IS 'Prioridad relativa de la dieta dentro del grupo. Menor número suele significar mayor relevancia.';

COMMENT ON COLUMN "rel_grupo_nutricional_dieta"."tipo_relacion" IS 'Tipo de regla: SUGERIDA, OBLIGATORIA o CONTRAINDICADA.';

COMMENT ON COLUMN "rel_grupo_nutricional_dieta"."observacion" IS 'Comentarios o aclaraciones sobre cuándo se aplica esta regla.';

COMMENT ON COLUMN "rel_grupo_nutricional_dieta"."activo" IS 'Permite activar o desactivar la regla sin borrarla.';

COMMENT ON TABLE "rel_grupo_nutricional_restriccion" IS 'TABLA: rel_grupo_nutricional_restriccion

QUÉ ES:
Regla que conecta un grupo nutricional con restricciones alimentarias.

PARA QUÉ SIRVE:
- Traducir lógica clínica a restricciones concretas.
- Apoyar decisiones o sugerencias sin depender siempre de IA.
';

COMMENT ON COLUMN "rel_grupo_nutricional_restriccion"."id" IS 'Clave primaria interna de la relación entre grupo nutricional y restricción alimentaria.';

COMMENT ON COLUMN "rel_grupo_nutricional_restriccion"."grupo_nutricional_id" IS 'Grupo nutricional al que aplica esta restricción.';

COMMENT ON COLUMN "rel_grupo_nutricional_restriccion"."restriccion_id" IS 'Restricción alimentaria asociada al grupo.';

COMMENT ON COLUMN "rel_grupo_nutricional_restriccion"."prioridad" IS 'Prioridad o peso relativo de la restricción para ese grupo.';

COMMENT ON COLUMN "rel_grupo_nutricional_restriccion"."obligatoria" IS 'Indica si la restricción es obligatoria o solo sugerida dentro del grupo.';

COMMENT ON COLUMN "rel_grupo_nutricional_restriccion"."observacion" IS 'Aclaraciones clínicas o de negocio sobre la relación.';

COMMENT ON COLUMN "rel_grupo_nutricional_restriccion"."activo" IS 'Permite activar o desactivar la regla sin borrarla.';

COMMENT ON TABLE "perfil_nutricional" IS 'TABLA: perfil_nutricional

QUÉ ES:
Estado base y relativamente estable del perfil nutricional del usuario.

PARA QUÉ SIRVE:
- Guardar identidad nutricional básica.
- Centralizar patrón alimentario, objetivo y ubicación.
- Servir como punto de unión para mediciones, enfermedades, restricciones y órdenes dietéticas.

QUÉ DEBE IR AQUÍ:
- Datos base y estables.
- No debe guardar listas de enfermedades o dietas en texto libre.

QUÉ NO DEBE IR AQUÍ:
- Historial antropométrico detallado
- Diagnósticos en texto libre
- Restricciones como cadena
- Prescripción dietética concreta
';

COMMENT ON COLUMN "perfil_nutricional"."id" IS 'Clave primaria interna del perfil nutricional.';

COMMENT ON COLUMN "perfil_nutricional"."usuario_id" IS 'Usuario dueño de este perfil. Debe existir una sola fila activa/base por usuario.';

COMMENT ON COLUMN "perfil_nutricional"."edad_reportada" IS 'Edad declarada por el usuario, útil cuando no se guarda fecha de nacimiento.';

COMMENT ON COLUMN "perfil_nutricional"."fecha_referencia_edad" IS 'Fecha en la que esa edad fue registrada, para saber si está desactualizada.';

COMMENT ON COLUMN "perfil_nutricional"."sexo" IS 'Dato opcional si se desea usar para recomendaciones, métricas o segmentación.';

COMMENT ON COLUMN "perfil_nutricional"."patron_alimentario_id" IS 'Patrón alimentario base del usuario. No es una dieta clínica.';

COMMENT ON COLUMN "perfil_nutricional"."objetivo_nutricional_id" IS 'Objetivo nutricional principal actual del usuario.';

COMMENT ON COLUMN "perfil_nutricional"."distrito_id" IS 'Ubicación actual normalizada del usuario. Desde aquí se infiere provincia y departamento.';

COMMENT ON COLUMN "perfil_nutricional"."fuente_ubicacion" IS 'Origen de la ubicación: usuario, chat, gps, manual, importacion.';

COMMENT ON COLUMN "perfil_nutricional"."observacion_general" IS 'Notas excepcionales que no deben modelarse como catálogo. No debe usarse para listas largas ni datos estructurados.';

COMMENT ON COLUMN "perfil_nutricional"."skipped_fields" IS 'Campos que el usuario decidió omitir o no contestar.';

COMMENT ON COLUMN "perfil_nutricional"."creado_en" IS 'Fecha de creación del perfil base.';

COMMENT ON COLUMN "perfil_nutricional"."actualizado_en" IS 'Última actualización del perfil base.';

COMMENT ON TABLE "perfil_nutricional_medicion" IS 'TABLA: perfil_nutricional_medicion

QUÉ ES:
Historial de mediciones físicas o antropométricas.

PARA QUÉ SIRVE:
- Evitar sobreescribir peso, talla y otros valores.
- Permitir evolución temporal.
- Diferenciar valor actual de histórico.

IMPORTANTE:
Cada fila es una medición, no un resumen del perfil.
';

COMMENT ON COLUMN "perfil_nutricional_medicion"."id" IS 'Clave primaria interna de una medición antropométrica.';

COMMENT ON COLUMN "perfil_nutricional_medicion"."perfil_nutricional_id" IS 'Perfil al que pertenece esta medición.';

COMMENT ON COLUMN "perfil_nutricional_medicion"."tipo_medicion" IS 'Tipo de medición. Ejemplo: PESO_KG, ALTURA_CM, CINTURA_CM, IMC_REFERENCIAL.';

COMMENT ON COLUMN "perfil_nutricional_medicion"."valor_decimal" IS 'Valor numérico de la medición.';

COMMENT ON COLUMN "perfil_nutricional_medicion"."unidad" IS 'Unidad del valor. Ejemplo: kg, cm, indice.';

COMMENT ON COLUMN "perfil_nutricional_medicion"."fecha_medicion" IS 'Fecha y hora en la que se registró la medición.';

COMMENT ON COLUMN "perfil_nutricional_medicion"."es_valor_actual" IS 'Marca si esta medición es la vigente para su tipo.';

COMMENT ON COLUMN "perfil_nutricional_medicion"."origen" IS 'Origen de la medición: SELF_REPORT, PROFESIONAL, IMPORTACION, SISTEMA.';

COMMENT ON COLUMN "perfil_nutricional_medicion"."observacion" IS 'Notas opcionales sobre la medición.';

COMMENT ON COLUMN "perfil_nutricional_medicion"."creado_en" IS 'Fecha de creación del registro.';

COMMENT ON TABLE "perfil_nutricional_enfermedad" IS 'TABLA: perfil_nutricional_enfermedad

QUÉ ES:
Relación entre el usuario y sus enfermedades o condiciones clínicas.

PARA QUÉ SIRVE:
- Representar el diagnóstico del usuario sin usar texto libre.
- Mantener vigencia, validación y procedencia del dato.

IMPORTANTE:
Esta tabla representa lo que el usuario tiene,
no lo que el catálogo general define.
';

COMMENT ON COLUMN "perfil_nutricional_enfermedad"."id" IS 'Clave primaria interna de la relación entre perfil y enfermedad.';

COMMENT ON COLUMN "perfil_nutricional_enfermedad"."perfil_nutricional_id" IS 'Perfil del usuario al que se le atribuye la enfermedad.';

COMMENT ON COLUMN "perfil_nutricional_enfermedad"."enfermedad_id" IS 'Enfermedad del maestro CIE10 asociada al perfil.';

COMMENT ON COLUMN "perfil_nutricional_enfermedad"."es_principal" IS 'Marca si esta es una condición principal o prioritaria dentro del perfil.';

COMMENT ON COLUMN "perfil_nutricional_enfermedad"."origen" IS 'Origen del dato: SELF_REPORT, PROFESIONAL, IMPORTACION, SISTEMA.';

COMMENT ON COLUMN "perfil_nutricional_enfermedad"."grado_confianza" IS 'Nivel de confianza si la enfermedad fue inferida o no plenamente validada.';

COMMENT ON COLUMN "perfil_nutricional_enfermedad"."validado" IS 'Marca si la condición fue validada por el sistema, usuario o profesional.';

COMMENT ON COLUMN "perfil_nutricional_enfermedad"."fecha_inicio" IS 'Fecha aproximada desde la que se considera vigente la condición, si se conoce.';

COMMENT ON COLUMN "perfil_nutricional_enfermedad"."fecha_fin" IS 'Fecha de fin si la condición ya no está vigente o se cerró.';

COMMENT ON COLUMN "perfil_nutricional_enfermedad"."vigente" IS 'Indica si actualmente se considera activa o vigente.';

COMMENT ON COLUMN "perfil_nutricional_enfermedad"."observacion" IS 'Notas aclaratorias sobre la condición del usuario.';

COMMENT ON COLUMN "perfil_nutricional_enfermedad"."creado_en" IS 'Fecha de creación del vínculo.';

COMMENT ON TABLE "perfil_nutricional_restriccion" IS 'TABLA: perfil_nutricional_restriccion

QUÉ ES:
Restricciones alimentarias que pertenecen al usuario.

PARA QUÉ SIRVE:
- Modelar alergias, intolerancias o restricciones personales/ clínicas.
- Distinguir restricciones del perfil de restricciones aplicadas en una orden dietética.

IMPORTANTE:
Lo que está aquí pertenece al usuario como condición o preferencia,
no necesariamente a una prescripción puntual.
';

COMMENT ON COLUMN "perfil_nutricional_restriccion"."id" IS 'Clave primaria interna de la relación entre perfil y restricción alimentaria.';

COMMENT ON COLUMN "perfil_nutricional_restriccion"."perfil_nutricional_id" IS 'Perfil del usuario al que se le asigna la restricción.';

COMMENT ON COLUMN "perfil_nutricional_restriccion"."restriccion_id" IS 'Restricción alimentaria del maestro correspondiente.';

COMMENT ON COLUMN "perfil_nutricional_restriccion"."obligatoria" IS 'Indica si la restricción es de cumplimiento obligatorio para el usuario.';

COMMENT ON COLUMN "perfil_nutricional_restriccion"."severidad" IS 'Severidad estimada: LEVE, MODERADA o SEVERA, si aplica.';

COMMENT ON COLUMN "perfil_nutricional_restriccion"."validado" IS 'Indica si la restricción ya fue validada.';

COMMENT ON COLUMN "perfil_nutricional_restriccion"."origen" IS 'Origen del dato: SELF_REPORT, PROFESIONAL, IMPORTACION, SISTEMA.';

COMMENT ON COLUMN "perfil_nutricional_restriccion"."grado_confianza" IS 'Nivel de confianza si la restricción fue inferida o no confirmada.';

COMMENT ON COLUMN "perfil_nutricional_restriccion"."fecha_inicio" IS 'Fecha aproximada de inicio de la restricción.';

COMMENT ON COLUMN "perfil_nutricional_restriccion"."fecha_fin" IS 'Fecha de fin si deja de aplicar.';

COMMENT ON COLUMN "perfil_nutricional_restriccion"."vigente" IS 'Marca si la restricción sigue activa actualmente.';

COMMENT ON COLUMN "perfil_nutricional_restriccion"."observacion" IS 'Notas adicionales sobre la restricción.';

COMMENT ON COLUMN "perfil_nutricional_restriccion"."creado_en" IS 'Fecha de creación del vínculo.';

COMMENT ON TABLE "orden_dietetica" IS 'TABLA: orden_dietetica

QUÉ ES:
Prescripción o indicación dietética concreta para un usuario.

PARA QUÉ SIRVE:
- Separar el perfil del usuario de la dieta vigente.
- Permitir historial de órdenes.
- Asociar dietas y restricciones concretas con fechas y estado.

IMPORTANTE:
Esta tabla no es catálogo.
Representa una orden real aplicada a una persona.
';

COMMENT ON COLUMN "orden_dietetica"."id" IS 'Clave primaria interna de la orden dietética.';

COMMENT ON COLUMN "orden_dietetica"."perfil_nutricional_id" IS 'Perfil del usuario al que se aplica esta orden.';

COMMENT ON COLUMN "orden_dietetica"."codigo" IS 'Código interno opcional para identificar la orden.';

COMMENT ON COLUMN "orden_dietetica"."estado" IS 'Estado de la orden: BORRADOR, ACTIVA, SUSPENDIDA, FINALIZADA, CANCELADA.';

COMMENT ON COLUMN "orden_dietetica"."textura_dieta_id" IS 'Textura principal asociada a esta orden, si aplica.';

COMMENT ON COLUMN "orden_dietetica"."fecha_inicio" IS 'Fecha/hora desde la que empieza a regir la orden dietética.';

COMMENT ON COLUMN "orden_dietetica"."fecha_fin" IS 'Fecha/hora de término si la orden ya no está vigente.';

COMMENT ON COLUMN "orden_dietetica"."vigente" IS 'Marca rápida para saber si la orden sigue activa.';

COMMENT ON COLUMN "orden_dietetica"."indicada_por" IS 'Responsable o fuente humana/funcional: nutricionista, médico, sistema, chatbot.';

COMMENT ON COLUMN "orden_dietetica"."fuente_orden" IS 'Origen formal de la orden: MANUAL, RECOMENDADA, VALIDADA, IMPORTADA.';

COMMENT ON COLUMN "orden_dietetica"."observacion" IS 'Notas generales sobre la orden.';

COMMENT ON COLUMN "orden_dietetica"."creado_en" IS 'Fecha de creación de la orden.';

COMMENT ON COLUMN "orden_dietetica"."actualizado_en" IS 'Última actualización de la orden.';

COMMENT ON TABLE "orden_dietetica_dieta" IS 'TABLA: orden_dietetica_dieta

QUÉ ES:
Lista de dietas terapéuticas incluidas en una orden dietética.

PARA QUÉ SIRVE:
- Permitir que una orden tenga más de una dieta.
- Priorizar una dieta principal.
- Mantener trazabilidad de combinaciones dietéticas.
';

COMMENT ON COLUMN "orden_dietetica_dieta"."id" IS 'Clave primaria interna de la relación entre una orden y una dieta terapéutica.';

COMMENT ON COLUMN "orden_dietetica_dieta"."orden_dietetica_id" IS 'Orden dietética a la que pertenece esta dieta.';

COMMENT ON COLUMN "orden_dietetica_dieta"."dieta_terapeutica_id" IS 'Dieta terapéutica que forma parte de la orden.';

COMMENT ON COLUMN "orden_dietetica_dieta"."es_principal" IS 'Marca si esta dieta es la principal dentro de la orden.';

COMMENT ON COLUMN "orden_dietetica_dieta"."prioridad" IS 'Prioridad relativa dentro de la orden. Menor número suele significar mayor importancia.';

COMMENT ON COLUMN "orden_dietetica_dieta"."observacion" IS 'Notas específicas de esta dieta dentro de la orden.';

COMMENT ON COLUMN "orden_dietetica_dieta"."activo" IS 'Permite desactivar esta dieta dentro de la orden sin borrar el historial.';

COMMENT ON COLUMN "orden_dietetica_dieta"."creado_en" IS 'Fecha de creación del vínculo.';

COMMENT ON TABLE "orden_dietetica_restriccion" IS 'TABLA: orden_dietetica_restriccion

QUÉ ES:
Restricciones alimentarias aplicadas específicamente a una orden dietética.

PARA QUÉ SIRVE:
- Distinguir restricciones propias del usuario de restricciones operativas de la orden.
- Modelar combinaciones más finas dentro de una indicación concreta.
';

COMMENT ON COLUMN "orden_dietetica_restriccion"."id" IS 'Clave primaria interna de la relación entre una orden y una restricción.';

COMMENT ON COLUMN "orden_dietetica_restriccion"."orden_dietetica_id" IS 'Orden dietética sobre la cual aplica esta restricción.';

COMMENT ON COLUMN "orden_dietetica_restriccion"."restriccion_id" IS 'Restricción alimentaria incluida en la orden.';

COMMENT ON COLUMN "orden_dietetica_restriccion"."obligatoria" IS 'Indica si la restricción debe cumplirse obligatoriamente dentro de la orden.';

COMMENT ON COLUMN "orden_dietetica_restriccion"."severidad" IS 'Nivel o intensidad con la que se aplica la restricción, si se desea modelar.';

COMMENT ON COLUMN "orden_dietetica_restriccion"."observacion" IS 'Notas específicas sobre esta restricción en el contexto de la orden.';

COMMENT ON COLUMN "orden_dietetica_restriccion"."activo" IS 'Permite desactivar el vínculo sin perder trazabilidad histórica.';

COMMENT ON COLUMN "orden_dietetica_restriccion"."creado_en" IS 'Fecha de creación del vínculo.';

COMMENT ON TABLE "mae_alias_semantico" IS 'TABLA: mae_alias_semantico

QUÉ ES:
Catálogo de sinónimos, frases naturales, errores comunes y variantes semánticas.

PARA QUÉ SIRVE:
- Resolver lenguaje del usuario sin llamar siempre a IA.
- Mapear expresiones coloquiales a entidades canónicas.
- Mejorar exact match, fuzzy match y búsqueda vectorial.

EJEMPLOS:
- "azúcar alta" -> enfermedad o grupo DIABETES
- "presión alta" -> grupo HIPERTENSION
- "no tolero leche" -> restricción SIN_LACTOSA
';

COMMENT ON COLUMN "mae_alias_semantico"."id" IS 'Clave primaria interna del alias semántico.';

COMMENT ON COLUMN "mae_alias_semantico"."entidad_tipo" IS 'Tipo de entidad canónica a la que apunta el alias. Ejemplo: ENFERMEDAD_CIE10 o RESTRICCION_ALIMENTARIA.';

COMMENT ON COLUMN "mae_alias_semantico"."entidad_codigo" IS 'Código canónico de la entidad dentro de su maestro.';

COMMENT ON COLUMN "mae_alias_semantico"."alias_texto" IS 'Alias visible, sin normalizar. Ejemplo: azúcar alta, presión alta, no tolero leche.';

COMMENT ON COLUMN "mae_alias_semantico"."alias_normalizado" IS 'Versión normalizada del alias para búsquedas exactas o fuzzy.';

COMMENT ON COLUMN "mae_alias_semantico"."idioma" IS 'Idioma del alias, útil si luego agregas variantes en otros idiomas.';

COMMENT ON COLUMN "mae_alias_semantico"."es_canonico" IS 'Marca si este alias corresponde al nombre oficial o solo a una variante útil.';

COMMENT ON COLUMN "mae_alias_semantico"."prioridad" IS 'Prioridad del alias cuando existan varias formas de mapear el mismo concepto.';

COMMENT ON COLUMN "mae_alias_semantico"."activo" IS 'Permite activar o desactivar el alias sin borrarlo.';

COMMENT ON COLUMN "mae_alias_semantico"."creado_en" IS 'Fecha de creación del alias.';

COMMENT ON COLUMN "mae_alias_semantico"."actualizado_en" IS 'Última actualización del alias.';

COMMENT ON TABLE "semantic_catalog" IS 'TABLA: semantic_catalog

QUÉ ES:
Índice semántico unificado y searchable del sistema.

PARA QUÉ SIRVE:
- Concentrar texto indexable para búsquedas exactas, fuzzy y vectoriales.
- Evitar consultar múltiples tablas de catálogo por separado.
- Servir como base para una capa híbrida de resolución.

IMPORTANTE:
Esta tabla no reemplaza los maestros.
Solo ayuda a encontrarlos rápido y barato.
';

COMMENT ON COLUMN "semantic_catalog"."id" IS 'Clave primaria interna del catálogo semántico indexable.';

COMMENT ON COLUMN "semantic_catalog"."entidad_tipo" IS 'Tipo canónico de entidad que representa esta entrada.';

COMMENT ON COLUMN "semantic_catalog"."entidad_codigo" IS 'Código canónico de la entidad representada.';

COMMENT ON COLUMN "semantic_catalog"."alias_semantico_id" IS 'Alias que originó esta entrada, si provino de mae_alias_semantico.';

COMMENT ON COLUMN "semantic_catalog"."nombre_canonico" IS 'Nombre oficial o canónico de la entidad.';

COMMENT ON COLUMN "semantic_catalog"."texto_busqueda" IS 'Texto principal que se quiere buscar o comparar.';

COMMENT ON COLUMN "semantic_catalog"."texto_normalizado" IS 'Versión normalizada del texto de búsqueda.';

COMMENT ON COLUMN "semantic_catalog"."peso_lexico" IS 'Peso relativo para estrategias léxicas o trigram.';

COMMENT ON COLUMN "semantic_catalog"."peso_semantico" IS 'Peso relativo para estrategias vectoriales o semánticas.';

COMMENT ON COLUMN "semantic_catalog"."embedding" IS 'Representación vectorial del texto. En PostgreSQL real sería vector(1536) u otra dimensión.';

COMMENT ON COLUMN "semantic_catalog"."embedding_model" IS 'Nombre del modelo usado para generar el embedding.';

COMMENT ON COLUMN "semantic_catalog"."activo" IS 'Marca si la entrada sigue activa en el índice semántico.';

COMMENT ON COLUMN "semantic_catalog"."generado_en" IS 'Fecha de generación de esta entrada semántica.';

COMMENT ON COLUMN "semantic_catalog"."actualizado_en" IS 'Última actualización de esta entrada.';

COMMENT ON TABLE "semantic_resolution_cache" IS 'TABLA: semantic_resolution_cache

QUÉ ES:
Cache de resoluciones semánticas reutilizables.

PARA QUÉ SIRVE:
- Evitar recalcular fuzzy, vector o IA para la misma consulta.
- Reducir latencia.
- Bajar costo de llamadas al modelo.

IMPORTANTE:
Esta tabla es clave en la estrategia de ahorro de IA.
';

COMMENT ON COLUMN "semantic_resolution_cache"."id" IS 'Clave primaria interna del cache de resolución semántica.';

COMMENT ON COLUMN "semantic_resolution_cache"."scope" IS 'Contexto en el que se hizo la resolución. Ejemplo: PROFILE_FIELD, ENTITY_MATCH, NUTRITION_CLASSIFICATION.';

COMMENT ON COLUMN "semantic_resolution_cache"."field_code" IS 'Campo concreto que se quería resolver. Ejemplo: enfermedad, objetivo, restriccion.';

COMMENT ON COLUMN "semantic_resolution_cache"."query_texto" IS 'Texto original consultado.';

COMMENT ON COLUMN "semantic_resolution_cache"."query_normalizada" IS 'Versión normalizada de la consulta para reutilización de resultados.';

COMMENT ON COLUMN "semantic_resolution_cache"."entidad_tipo_resuelta" IS 'Tipo final de entidad resuelta.';

COMMENT ON COLUMN "semantic_resolution_cache"."entidad_codigo_resuelto" IS 'Código final resuelto dentro del maestro correspondiente.';

COMMENT ON COLUMN "semantic_resolution_cache"."estrategia_usada" IS 'Método usado para resolver: EXACT, TRGM, VECTOR, HYBRID, LLM.';

COMMENT ON COLUMN "semantic_resolution_cache"."confidence" IS 'Confianza final con la que se guardó el resultado en cache.';

COMMENT ON COLUMN "semantic_resolution_cache"."compatible_con_reglas" IS 'Indica si la resolución fue coherente con reglas relacionales o de negocio.';

COMMENT ON COLUMN "semantic_resolution_cache"."top_candidates_json" IS 'Lista opcional de candidatos considerados durante la resolución.';

COMMENT ON COLUMN "semantic_resolution_cache"."hit_count" IS 'Número de veces que esta resolución en cache ha sido reutilizada.';

COMMENT ON COLUMN "semantic_resolution_cache"."expires_at" IS 'Fecha de expiración de la entrada de cache, si aplica.';

COMMENT ON COLUMN "semantic_resolution_cache"."creado_en" IS 'Fecha de creación de la entrada en cache.';

COMMENT ON COLUMN "semantic_resolution_cache"."actualizado_en" IS 'Última actualización del cache.';

COMMENT ON TABLE "semantic_match_log" IS 'TABLA: semantic_match_log

QUÉ ES:
Log detallado de intentos de resolución semántica.

PARA QUÉ SIRVE:
- Auditar qué estrategia funcionó.
- Afinar thresholds.
- Medir ahorro de IA.
- Detectar puntos débiles del sistema.

IMPORTANTE:
Es una tabla de observabilidad, no de negocio.
';

COMMENT ON COLUMN "semantic_match_log"."id" IS 'Clave primaria interna del log de matching semántico.';

COMMENT ON COLUMN "semantic_match_log"."usuario_id" IS 'Usuario que originó la consulta o el texto que se quiso resolver.';

COMMENT ON COLUMN "semantic_match_log"."incoming_message_id" IS 'Mensaje entrante asociado al intento de matching, si existe.';

COMMENT ON COLUMN "semantic_match_log"."scope" IS 'Contexto de resolución.';

COMMENT ON COLUMN "semantic_match_log"."field_code" IS 'Campo que se intentó resolver.';

COMMENT ON COLUMN "semantic_match_log"."query_texto" IS 'Texto original evaluado.';

COMMENT ON COLUMN "semantic_match_log"."query_normalizada" IS 'Texto normalizado usado en el pipeline.';

COMMENT ON COLUMN "semantic_match_log"."estrategia_usada" IS 'Método usado para resolver el matching.';

COMMENT ON COLUMN "semantic_match_log"."exact_match" IS 'Marca si hubo match exacto sin necesidad de fuzzy o vector.';

COMMENT ON COLUMN "semantic_match_log"."trigram_score" IS 'Puntaje de similitud léxica o trigram, si aplica.';

COMMENT ON COLUMN "semantic_match_log"."vector_score" IS 'Puntaje de similitud semántica/vectorial, si aplica.';

COMMENT ON COLUMN "semantic_match_log"."confidence_final" IS 'Confianza final del matching.';

COMMENT ON COLUMN "semantic_match_log"."entidad_tipo_resuelta" IS 'Tipo de entidad resuelta finalmente.';

COMMENT ON COLUMN "semantic_match_log"."entidad_codigo_resuelto" IS 'Código de la entidad resuelta finalmente.';

COMMENT ON COLUMN "semantic_match_log"."escalado_a_ia" IS 'Marca si el caso terminó escalando a IA.';

COMMENT ON COLUMN "semantic_match_log"."decidido_por_regla" IS 'Marca si la decisión final vino de reglas relacionales y no solo de similitud.';

COMMENT ON COLUMN "semantic_match_log"."latency_ms" IS 'Tiempo aproximado de resolución en milisegundos.';

COMMENT ON COLUMN "semantic_match_log"."error_detail" IS 'Error o detalle si el matching falló.';

COMMENT ON COLUMN "semantic_match_log"."creado_en" IS 'Momento en que ocurrió este intento de matching.';

COMMENT ON TABLE "semantic_review_queue" IS 'TABLA: semantic_review_queue

QUÉ ES:
Cola de revisión para casos ambiguos.

PARA QUÉ SIRVE:
- Evitar mandar automáticamente todo a IA.
- Mantener casos dudosos para revisión posterior.
- Mejorar reglas y alias con aprendizaje operativo.
';

COMMENT ON COLUMN "semantic_review_queue"."id" IS 'Clave primaria interna del caso enviado a revisión.';

COMMENT ON COLUMN "semantic_review_queue"."usuario_id" IS 'Usuario relacionado con el caso ambiguo.';

COMMENT ON COLUMN "semantic_review_queue"."incoming_message_id" IS 'Mensaje que originó el caso ambiguo, si aplica.';

COMMENT ON COLUMN "semantic_review_queue"."scope" IS 'Contexto del caso.';

COMMENT ON COLUMN "semantic_review_queue"."field_code" IS 'Campo que no pudo resolverse con suficiente claridad.';

COMMENT ON COLUMN "semantic_review_queue"."query_texto" IS 'Texto original problemático o ambiguo.';

COMMENT ON COLUMN "semantic_review_queue"."query_normalizada" IS 'Versión normalizada del texto.';

COMMENT ON COLUMN "semantic_review_queue"."top_candidates_json" IS 'Candidatos sugeridos por el pipeline antes de revisión.';

COMMENT ON COLUMN "semantic_review_queue"."razon" IS 'Razón por la cual se envió a revisión: LOW_CONFIDENCE, CONFLICT, NO_MATCH, RULE_MISMATCH.';

COMMENT ON COLUMN "semantic_review_queue"."estado" IS 'Estado de la revisión: PENDING, REVIEWED, DISMISSED, RESOLVED.';

COMMENT ON COLUMN "semantic_review_queue"."resolucion_manual_tipo" IS 'Tipo de entidad elegido manualmente si hubo resolución humana.';

COMMENT ON COLUMN "semantic_review_queue"."resolucion_manual_codigo" IS 'Código elegido manualmente si hubo resolución humana.';

COMMENT ON COLUMN "semantic_review_queue"."observacion" IS 'Comentarios del revisor o del sistema sobre el caso.';

COMMENT ON COLUMN "semantic_review_queue"."creado_en" IS 'Fecha de creación del caso.';

COMMENT ON COLUMN "semantic_review_queue"."resuelto_en" IS 'Fecha de cierre o resolución del caso.';

COMMENT ON TABLE "embedding_jobs" IS 'TABLA: embedding_jobs

QUÉ ES:
Cola de trabajos para generación o regeneración de embeddings.

PARA QUÉ SIRVE:
- Desacoplar el costo de embedding del flujo principal.
- Permitir recalcular embeddings cuando cambie el modelo.
- Soportar procesos batch o diferidos.
';

COMMENT ON COLUMN "embedding_jobs"."id" IS 'Clave primaria interna del job de embedding.';

COMMENT ON COLUMN "embedding_jobs"."source_table" IS 'Tabla fuente de la que viene el texto a embeber.';

COMMENT ON COLUMN "embedding_jobs"."source_id" IS 'ID de la fila fuente dentro de la tabla indicada.';

COMMENT ON COLUMN "embedding_jobs"."texto_fuente" IS 'Texto que debe convertirse en embedding.';

COMMENT ON COLUMN "embedding_jobs"."modelo" IS 'Modelo de embeddings que debe usarse.';

COMMENT ON COLUMN "embedding_jobs"."estado" IS 'Estado del job: PENDING, PROCESSING, DONE, FAILED.';

COMMENT ON COLUMN "embedding_jobs"."retry_count" IS 'Número de reintentos del job.';

COMMENT ON COLUMN "embedding_jobs"."error_detail" IS 'Detalle del último error si el embedding falló.';

COMMENT ON COLUMN "embedding_jobs"."creado_en" IS 'Fecha de creación del job.';

COMMENT ON COLUMN "embedding_jobs"."actualizado_en" IS 'Última actualización del job.';

COMMENT ON COLUMN "embedding_jobs"."procesado_en" IS 'Fecha en la que el job terminó correctamente, si aplica.';

COMMENT ON TABLE "formularios" IS 'TABLA: formularios

QUÉ ES:
Catálogo de formularios del sistema.

PARA QUÉ SIRVE:
- Versionar encuestas o formularios.
- Controlar disponibilidad temporal.
- Mantener histórico si cambia el contenido.
';

COMMENT ON COLUMN "formularios"."id" IS 'Clave primaria interna del formulario.';

COMMENT ON COLUMN "formularios"."codigo" IS 'Código funcional del formulario. Debe ser estable a lo largo del tiempo.';

COMMENT ON COLUMN "formularios"."nombre" IS 'Nombre visible o descriptivo del formulario.';

COMMENT ON COLUMN "formularios"."version" IS 'Versión del formulario, útil para cambios de estructura sin romper histórico.';

COMMENT ON COLUMN "formularios"."activo" IS 'Marca si el formulario está disponible para uso.';

COMMENT ON COLUMN "formularios"."fecha_inicio" IS 'Fecha desde la que el formulario está disponible.';

COMMENT ON COLUMN "formularios"."fecha_cierre" IS 'Fecha de cierre del formulario si deja de estar vigente.';

COMMENT ON COLUMN "formularios"."creado_en" IS 'Fecha de creación del formulario.';

COMMENT ON TABLE "formulario_en_progreso" IS 'TABLA: formulario_en_progreso

QUÉ ES:
Estado parcial de un formulario que todavía no termina.

PARA QUÉ SIRVE:
- Retomar un flujo sin perder respuestas.
- Llevar control de progreso.
- Soportar formularios conversacionales multi-turno.
';

COMMENT ON COLUMN "formulario_en_progreso"."id" IS 'Clave primaria interna del avance parcial del formulario.';

COMMENT ON COLUMN "formulario_en_progreso"."formulario_id" IS 'Formulario que el usuario está respondiendo.';

COMMENT ON COLUMN "formulario_en_progreso"."usuario_id" IS 'Usuario con un flujo actualmente en progreso para ese formulario/encuesta.';

COMMENT ON COLUMN "formulario_en_progreso"."estado_actual" IS 'Paso actual o estado del formulario en progreso.';

COMMENT ON COLUMN "formulario_en_progreso"."respuestas_parciales" IS 'Respuestas aún no consolidadas del formulario.';

COMMENT ON COLUMN "formulario_en_progreso"."uso_audio" IS 'Marca si el usuario utilizó audio durante esta interacción de formulario.';

COMMENT ON COLUMN "formulario_en_progreso"."uso_imagen" IS 'Marca si el usuario utilizó imagen durante esta interacción.';

COMMENT ON COLUMN "formulario_en_progreso"."iniciado_en" IS 'Fecha de inicio del formulario en progreso.';

COMMENT ON COLUMN "formulario_en_progreso"."actualizado_en" IS 'Última actualización del avance parcial.';

COMMENT ON COLUMN "formulario_en_progreso"."completado_en" IS 'Fecha de finalización si el formulario ya fue completado.';

COMMENT ON COLUMN "formulario_en_progreso"."audio_test_requested" IS 'Marca si se pidió probar audio.';

COMMENT ON COLUMN "formulario_en_progreso"."audio_test_completed" IS 'Marca si la prueba de audio se completó.';

COMMENT ON COLUMN "formulario_en_progreso"."audio_test_declined" IS 'Marca si el usuario rechazó la prueba de audio.';

COMMENT ON COLUMN "formulario_en_progreso"."image_test_requested" IS 'Marca si se pidió probar imagen.';

COMMENT ON COLUMN "formulario_en_progreso"."image_test_completed" IS 'Marca si la prueba de imagen se completó.';

COMMENT ON COLUMN "formulario_en_progreso"."image_test_declined" IS 'Marca si el usuario rechazó la prueba de imagen.';

COMMENT ON TABLE "respuestas_formulario" IS 'TABLA: respuestas_formulario

QUÉ ES:
Respuesta final consolidada de un formulario.

PARA QUÉ SIRVE:
- Guardar el resultado final.
- Distinguir lo parcial de lo ya cerrado.
- Relacionarlo con evaluación de usabilidad.
';

COMMENT ON COLUMN "respuestas_formulario"."id" IS 'Clave primaria interna de la respuesta final del formulario.';

COMMENT ON COLUMN "respuestas_formulario"."formulario_id" IS 'Formulario al que pertenece esta respuesta.';

COMMENT ON COLUMN "respuestas_formulario"."usuario_id" IS 'Usuario que respondió el formulario.';

COMMENT ON COLUMN "respuestas_formulario"."correo" IS 'Correo proporcionado en el formulario.';

COMMENT ON COLUMN "respuestas_formulario"."telefono" IS 'Teléfono proporcionado en el formulario, si aplica.';

COMMENT ON COLUMN "respuestas_formulario"."edad" IS 'Edad reportada en el formulario, si se pregunta.';

COMMENT ON COLUMN "respuestas_formulario"."asegurado_essalud" IS 'Respuesta a si está asegurado en EsSalud.';

COMMENT ON COLUMN "respuestas_formulario"."comentario" IS 'Comentario libre del usuario.';

COMMENT ON COLUMN "respuestas_formulario"."autorizo_uso_investigacion" IS 'Consentimiento para uso de datos en investigación, si aplica.';

COMMENT ON COLUMN "respuestas_formulario"."puntaje_nps" IS 'Puntaje NPS o equivalente.';

COMMENT ON COLUMN "respuestas_formulario"."creado_en" IS 'Fecha de creación de la respuesta final.';

COMMENT ON COLUMN "respuestas_formulario"."audio_evaluado" IS 'Marca si el componente de audio fue evaluado.';

COMMENT ON COLUMN "respuestas_formulario"."audio_no_aplica" IS 'Marca si audio no aplicaba a esta evaluación.';

COMMENT ON COLUMN "respuestas_formulario"."imagen_evaluada" IS 'Marca si el componente de imagen fue evaluado.';

COMMENT ON COLUMN "respuestas_formulario"."imagen_no_aplica" IS 'Marca si imagen no aplicaba a esta evaluación.';

COMMENT ON COLUMN "respuestas_formulario"."correo_proporcionado" IS 'Marca rápida de si el usuario sí dejó correo.';

COMMENT ON TABLE "evaluacion_usabilidad" IS 'TABLA: evaluacion_usabilidad

QUÉ ES:
Subtabla especializada de métricas de usabilidad.

PARA QUÉ SIRVE:
- Guardar respuestas estructuradas de evaluación.
- Separar metadatos del formulario de puntuaciones específicas.
';

COMMENT ON COLUMN "evaluacion_usabilidad"."id" IS 'Clave primaria interna de la evaluación de usabilidad.';

COMMENT ON COLUMN "evaluacion_usabilidad"."respuesta_formulario_id" IS 'Respuesta final del formulario a la que pertenece esta evaluación.';

COMMENT ON COLUMN "evaluacion_usabilidad"."p1_personalidad_realista_atractiva" IS 'Respuesta de la pregunta 1 de usabilidad.';

COMMENT ON COLUMN "evaluacion_usabilidad"."p2_explico_proposito_alcance" IS 'Respuesta de la pregunta 2 de usabilidad.';

COMMENT ON COLUMN "evaluacion_usabilidad"."p3_facil_navegar" IS 'Respuesta de la pregunta 3 de usabilidad.';

COMMENT ON COLUMN "evaluacion_usabilidad"."p4_me_entendio_bien" IS 'Respuesta de la pregunta 4 de usabilidad.';

COMMENT ON COLUMN "evaluacion_usabilidad"."p5_respuestas_utiles_apropiadas_informativas" IS 'Respuesta de la pregunta 5 de usabilidad.';

COMMENT ON COLUMN "evaluacion_usabilidad"."p6_manejo_errores_equivocaciones" IS 'Respuesta de la pregunta 6 de usabilidad.';

COMMENT ON COLUMN "evaluacion_usabilidad"."p7_muy_facil_de_usar" IS 'Respuesta de la pregunta 7 de usabilidad.';

COMMENT ON COLUMN "evaluacion_usabilidad"."p8_audio_claridad" IS 'Respuesta de la pregunta 8 relacionada a audio.';

COMMENT ON COLUMN "evaluacion_usabilidad"."p9_reconocio_contexto_imagen" IS 'Respuesta de la pregunta 9 relacionada a imagen.';

COMMENT ON COLUMN "evaluacion_usabilidad"."p10_se_enfoco_en_nutricion" IS 'Respuesta de la pregunta 10 sobre enfoque nutricional.';

COMMENT ON COLUMN "evaluacion_usabilidad"."creado_en" IS 'Fecha de creación de la evaluación.';

COMMENT ON TABLE "documentos_rag" IS 'TABLA: documentos_rag

QUÉ ES:
Catálogo de documentos fuente del sistema RAG.

PARA QUÉ SIRVE:
- Registrar archivos o fuentes que alimentan la recuperación.
- Mantener estado de procesamiento.
- Relacionar fragmentos con su documento origen.
';

COMMENT ON COLUMN "documentos_rag"."id" IS 'Clave primaria interna del documento fuente del RAG.';

COMMENT ON COLUMN "documentos_rag"."nombre" IS 'Nombre visible o técnico del documento.';

COMMENT ON COLUMN "documentos_rag"."tipo_fuente" IS 'Tipo de fuente: pdf, web, receta, faq, manual.';

COMMENT ON COLUMN "documentos_rag"."archivo_url" IS 'Ubicación física o lógica del documento.';

COMMENT ON COLUMN "documentos_rag"."descripcion" IS 'Descripción breve del documento o su propósito.';

COMMENT ON COLUMN "documentos_rag"."estado" IS 'Estado del documento dentro del pipeline RAG: activo, procesando, error, archivado.';

COMMENT ON COLUMN "documentos_rag"."creado_en" IS 'Fecha de creación del documento en el sistema.';

COMMENT ON COLUMN "documentos_rag"."actualizado_en" IS 'Última actualización del documento.';

COMMENT ON TABLE "fragmentos_rag" IS 'TABLA: fragmentos_rag

QUÉ ES:
Fragmentos indexables de los documentos fuente.

PARA QUÉ SIRVE:
- Soportar búsqueda semántica o recuperación por chunks.
- Mantener trazabilidad hacia el documento original.
';

COMMENT ON COLUMN "fragmentos_rag"."id" IS 'Clave primaria interna del fragmento o chunk.';

COMMENT ON COLUMN "fragmentos_rag"."documento_id" IS 'Documento del que salió este fragmento.';

COMMENT ON COLUMN "fragmentos_rag"."pagina" IS 'Número de página original si el documento lo tiene.';

COMMENT ON COLUMN "fragmentos_rag"."numero_fragmento" IS 'Orden secuencial del fragmento dentro del documento.';

COMMENT ON COLUMN "fragmentos_rag"."contenido" IS 'Texto del fragmento usado para recuperación.';

COMMENT ON COLUMN "fragmentos_rag"."metadata" IS 'Metadatos opcionales del fragmento.';

COMMENT ON COLUMN "fragmentos_rag"."embedding" IS 'Representación vectorial del fragmento. En PostgreSQL real sería vector(1536).';

COMMENT ON COLUMN "fragmentos_rag"."creado_en" IS 'Fecha de creación del fragmento.';

COMMENT ON TABLE "campanias" IS 'TABLA: campanias

QUÉ ES:
Registro de campañas o actividades vinculadas a salud/nutrición.

PARA QUÉ SIRVE:
- Mostrar oportunidades o actividades por zona.
- Asociar campañas con ubicación.
- Dar contexto útil al usuario según territorio.
';

COMMENT ON COLUMN "campanias"."id" IS 'Clave primaria interna de la campaña.';

COMMENT ON COLUMN "campanias"."titulo" IS 'Nombre o título visible de la campaña.';

COMMENT ON COLUMN "campanias"."descripcion" IS 'Descripción de la campaña y su propósito.';

COMMENT ON COLUMN "campanias"."tipo" IS 'Tipo general de campaña. Ejemplo: nutricion, anemia, salud_general.';

COMMENT ON COLUMN "campanias"."fecha_inicio" IS 'Fecha de inicio de la campaña.';

COMMENT ON COLUMN "campanias"."fecha_fin" IS 'Fecha de cierre o fin de la campaña.';

COMMENT ON COLUMN "campanias"."distrito_id" IS 'Distrito donde aplica la campaña, si está geográficamente localizada.';

COMMENT ON COLUMN "campanias"."lugar" IS 'Lugar específico o dirección textual de la campaña.';

COMMENT ON COLUMN "campanias"."creado_en" IS 'Fecha de creación de la campaña en el sistema.';

ALTER TABLE "incoming_messages" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversation_state" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "profile_extractions" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "extraction_jobs" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "outgoing_messages" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "memoria_chat" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mae_provincia" ADD FOREIGN KEY ("departamento_id") REFERENCES "mae_departamento" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mae_distrito" ADD FOREIGN KEY ("provincia_id") REFERENCES "mae_provincia" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "perfil_nutricional" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "perfil_nutricional" ADD FOREIGN KEY ("patron_alimentario_id") REFERENCES "mae_patron_alimentario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "perfil_nutricional" ADD FOREIGN KEY ("objetivo_nutricional_id") REFERENCES "mae_objetivo_nutricional" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "perfil_nutricional" ADD FOREIGN KEY ("distrito_id") REFERENCES "mae_distrito" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "perfil_nutricional_medicion" ADD FOREIGN KEY ("perfil_nutricional_id") REFERENCES "perfil_nutricional" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "perfil_nutricional_enfermedad" ADD FOREIGN KEY ("perfil_nutricional_id") REFERENCES "perfil_nutricional" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "perfil_nutricional_enfermedad" ADD FOREIGN KEY ("enfermedad_id") REFERENCES "mae_enfermedad_cie10" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "perfil_nutricional_restriccion" ADD FOREIGN KEY ("perfil_nutricional_id") REFERENCES "perfil_nutricional" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "perfil_nutricional_restriccion" ADD FOREIGN KEY ("restriccion_id") REFERENCES "mae_restriccion_alimentaria" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orden_dietetica" ADD FOREIGN KEY ("perfil_nutricional_id") REFERENCES "perfil_nutricional" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orden_dietetica" ADD FOREIGN KEY ("textura_dieta_id") REFERENCES "mae_textura_dieta" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orden_dietetica_dieta" ADD FOREIGN KEY ("orden_dietetica_id") REFERENCES "orden_dietetica" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orden_dietetica_dieta" ADD FOREIGN KEY ("dieta_terapeutica_id") REFERENCES "mae_dieta_terapeutica" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orden_dietetica_restriccion" ADD FOREIGN KEY ("orden_dietetica_id") REFERENCES "orden_dietetica" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orden_dietetica_restriccion" ADD FOREIGN KEY ("restriccion_id") REFERENCES "mae_restriccion_alimentaria" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rel_enfermedad_grupo_nutricional" ADD FOREIGN KEY ("enfermedad_id") REFERENCES "mae_enfermedad_cie10" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rel_enfermedad_grupo_nutricional" ADD FOREIGN KEY ("grupo_nutricional_id") REFERENCES "mae_grupo_nutricional" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rel_grupo_nutricional_dieta" ADD FOREIGN KEY ("grupo_nutricional_id") REFERENCES "mae_grupo_nutricional" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rel_grupo_nutricional_dieta" ADD FOREIGN KEY ("dieta_terapeutica_id") REFERENCES "mae_dieta_terapeutica" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rel_grupo_nutricional_restriccion" ADD FOREIGN KEY ("grupo_nutricional_id") REFERENCES "mae_grupo_nutricional" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rel_grupo_nutricional_restriccion" ADD FOREIGN KEY ("restriccion_id") REFERENCES "mae_restriccion_alimentaria" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "semantic_catalog" ADD FOREIGN KEY ("alias_semantico_id") REFERENCES "mae_alias_semantico" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "semantic_match_log" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "semantic_match_log" ADD FOREIGN KEY ("incoming_message_id") REFERENCES "incoming_messages" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "semantic_review_queue" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "semantic_review_queue" ADD FOREIGN KEY ("incoming_message_id") REFERENCES "incoming_messages" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "formulario_en_progreso" ADD FOREIGN KEY ("formulario_id") REFERENCES "formularios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "formulario_en_progreso" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "respuestas_formulario" ADD FOREIGN KEY ("formulario_id") REFERENCES "formularios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "respuestas_formulario" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "evaluacion_usabilidad" ADD FOREIGN KEY ("respuesta_formulario_id") REFERENCES "respuestas_formulario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fragmentos_rag" ADD FOREIGN KEY ("documento_id") REFERENCES "documentos_rag" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "campanias" ADD FOREIGN KEY ("distrito_id") REFERENCES "mae_distrito" ("id") DEFERRABLE INITIALLY IMMEDIATE;
